apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-highcpu
spec:
  selector:
    matchLabels:
      run: php-apache-highcpu
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache-highcpu
    spec:
      nodeSelector: 
        machine-type: highcpu
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1600m
          requests:
            cpu: 1000m